export const HOME_SCREEN = 'HOME_SCREEN';
export const REPOSITORIES_SCREEN = 'REPOSITORIES_SCREEN';
export const PULL_REQUESTS_SCREEN = 'PULL_REQUESTS_SCREEN';
export const ISSUES_SCREEN = 'ISSUES_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const SEARCH_RESULTS_SCREEN = 'SEARCH_RESULTS_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
