export const HOME_SCREEN = 'HOME_SCREEN';
export const REPOSITORIES_SCREEN = 'REPOSITORIES_SCREEN';
export const PULL_REQUESTS_SCREEN = 'PULL_REQUESTS_SCREEN';
export const ISSUES_SCREEN = 'ISSUES_SCREEN';
